repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: pretty-format-json
      - id: check-json
      - id: check-xml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: end-of-file-fixer
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
        args: ["--prose-wrap", "preserve"]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.27.0
    hooks:
      - id: golangci-lint
